### ISSUE TITLE
See if the Elphel GTXE2 simulation library is useful

### ISSUE THREAD

**Issue by mithro** [enjoy-digital/usb3_pipe#10]
Elphel have a
> non-synthesizable free software replacement for an encrypted xilinx's primitive GTXE2_CHANNEL.v

It can be found at https://git.elphel.com/Elphel/gtxe2_gpl

Figure out if this model is useful for potential automated testing / simulation.

Because of the GPLv3 license, there are a couple of restrictions;
 * Repository should be imported into `third_party/XXXX`.
 * Repository should be an *optional* dependency and not required for usage of the core.
 * No code from the repository should be used / copied into this repository.

**Comment by enjoy-digital** [comment]
In the project, we are only using the transceivers as high speed serializers/deserializers, so we just need the transceiver to be configured for 5Gbps linerate and to be able to generate the LFPS signals (Out of band signals) and Electrical Idle state. The model could eventually be useful to simulate the transceiver initialization, but this is something that has already been validated for a long time on hardware and that would still need hardware tests if touched. So due the license conflict and limited additional value, i don't think we really need it.
