### ISSUE TITLE
ECP5: Validate SerDes at 5Gbps

### ISSUE THREAD

**Issue by enjoy-digital** [enjoy-digital/usb3_pipe#12]
Validate that we are able to run the SerDes at 5Gbps and check against a 7-series FPGA that TX/RX is working correctly.

**Comment by enjoy-digital** [comment]
ECP5 support has been added to LiteICLink with https://github.com/enjoy-digital/liteiclink/commit/37d45f382c01d106167b576c732bd4883f2b04d6 and https://github.com/enjoy-digital/liteiclink/commit/bb5eabf73a5467b52cc4bc17638e2752296c913c. It has been validated at 2.5Gbps with a simple test design. We now need to test with a 7-series at the same linerate and then increase the linerate to 5Gbps.

**Comment by enjoy-digital** [comment]
5Gbps has been validated with LiteICLink example design and commit: https://github.com/enjoy-digital/liteiclink/commit/39a41bec7c439ac245bb1ef060d95b25447a1824 (still with SMA loopback). We now need to test it against a Xilinx device.

**Comment by enjoy-digital** [comment]
The simple design has been validated between a KC705 and Versa ECP5, using SMA cables and PCIe (with a unmodified PCIe risers and the USB3 cable that does the TX/RX lanes swap).

![IMG_5520](https://user-images.githubusercontent.com/1450143/67078076-df924300-f190-11e9-88d9-91a03812835a.JPG)
![IMG_5522](https://user-images.githubusercontent.com/1450143/67078086-e325ca00-f190-11e9-9f78-dbf1c6054fa1.JPG)

The test designs are here:
https://github.com/enjoy-digital/liteiclink/tree/master/examples/transceiver

The next step is to test with USB3 and see if we able to send/receive packets.

**Comment by enjoy-digital** [comment]
The Beagle is able to see TSEQ/TS1 from the ECP5 but with some errors, but we have currently have large timing violations that could explain this:
````
Warning: Max frequency for clock '$glbnet$crg_clkout': 112.54 MHz (FAIL at 133.33 MHz)
Warning: Max frequency for clock     '$glbnet$rx_clk': 180.18 MHz (FAIL at 250.00 MHz)
Warning: Max frequency for clock     '$glbnet$tx_clk': 164.28 MHz (FAIL at 250.00 MHz)
````
So the next step is to optimize timings on ECP5.

**Comment by mithro** [comment]
@enjoy-digital Love those photos! :-)

**Comment by enjoy-digital** [comment]
@mithro :)
The timings have been improved and the Host now receives correctly the TSEQ/TS1 from the Versa ECP5. I still need to look at the RX path, but we should not be far from being able to use the Versa ECP5 for the dev.

**Comment by rowanG077** [comment]
I would really like to use USB 3.0 with the ECP5. Is there anything that you could would need help with? I'm not versed in migen but I do know digital design or could write documentation.

**Comment by enjoy-digital** [comment]
@rowanG077: for now things are still very experimental, and not really in a working state (for USB3, 5Gbps SerDes is working) but this should be working in not too long.

The best for now to test with ECP5 is probably to use a Versa ECP5 and modify a PCIe riser cable like this: https://github.com/enjoy-digital/usb3_pipe/issues/3#issuecomment-538501003 Since getting 5Gbps is already tricky regarding timings with the 5G version, i'm not sure i would try with the non-5G versions.

If you want to review the actual code and/or improve the tests, your help is welcome.

**Comment by enjoy-digital** [comment]
The way we initialize the RX for ECP5 in the loopback demo is currently too slow for USB3 (using BruteForceClockAligner that checks for valid commas and resets the RX is errors are detected). To get USB3 working with ECP5 we'll need to get rid of the BruteForeClockAligner since the link RX path needs to be initialized when TSEQ are transmitted.

**Comment by enjoy-digital** [comment]
The ECP5 SerDes are working correctly at 5Gbps when tested in loopback and against a Xilinx device. The only remaining limitation is https://github.com/enjoy-digital/usb3_pipe/issues/18.
