### ISSUE TITLE
Link is for non-5G Versa board

### ISSUE THREAD

**Issue by osterwood** [enjoy-digital/usb3_pipe#22]
Should't the recommended ECP5 development kit be LFE5UM5G-45F-VERSA-EVN instead of the 3G one that is currently linked to in the README?

http://www.latticesemi.com/en/Products/DevelopmentBoardsAndKits/ECP55GVersaDevKit

**Comment by enjoy-digital** [comment]
Indeed, thanks! Fixed with https://github.com/enjoy-digital/usb3_pipe/commit/46e2dafed3aacca2cac9a8039cdf685d81ed8e97.
