### ISSUE TITLE
usb A on both sides?

### ISSUE THREAD

**Issue by CarlFK** [enjoy-digital/usb3_pipe#25]
> Connect the USB3.0 type A cable between the breakout board and the computer.

Shouldn't it be a type B on the board side?   or some connector typical of a usb device (as opposed to usb host)

**Comment by enjoy-digital** [comment]
The previous setup was using a USB3.0 type A cable. This has been replaced with a SFP2USB module + regular USB3 cable: https://github.com/enjoy-digital/usb3_pipe/blob/master/doc/acorn_baseboard_sfp2usb_0.jpg
