### ISSUE TITLE
Define 7-Series/ECP5 Test Setup

### ISSUE THREAD

**Issue by enjoy-digital** [enjoy-digital/usb3_pipe#3]
The USB3 FMC could be used but the FMC is expensive and would also require a KONDOR AX Development Board for Lattice.

The best is probably to just use cheap PCIe riser (10$ on ebay/amazon):
![image](https://user-images.githubusercontent.com/1450143/65037097-3cf66280-d94d-11e9-981f-64cde7e4e3fb.png)

Use a PCIe express FPGA dev board:
- NeTV2 (Artix7): https://www.crowdsupply.com/alphamax/netv2
- PCIe Screamer (Artix7): http://shop.lambdaconcept.com/home/32-pciescreamerR02.html
- Versa ECP5 (ECP5): http://www.latticesemi.com/Products/DevelopmentBoardsAndKits/ECP5VersaDevelopmentKit.aspx

It should work since it seems USB3 can work without USB2 not connected: https://electronics.stackexchange.com/questions/107669/usb3-with-fewer-wires
and would make it easier for others to reproduce the results with a ~300$ setup.

I just created a very basic sniffer with the PCIe riser and a PCIe Screamer board and was able to retrieve data that seems valid: https://github.com/enjoy-digital/usb3_pipe/blob/master/sniffer/sniffer.py

**Comment by enjoy-digital** [comment]
It's not possible to use a PCIe riser directly since:
- USB3 TX/RX lanes are swapped.
- USB2 signals are used for others purpose (PCIe clock and reset).
 
But it's possible do remove the connector, cut a USB3 cable and connect it as follows:

![path980](https://user-images.githubusercontent.com/1450143/66228176-1e2ef480-e6df-11e9-87eb-70180d7a8c3a.png)

Once tested, put some hot glue on it and you here is your USB3 to PCIe cable that you can use with any FPGA PCIe dev board :):
![IMG_5517](https://user-images.githubusercontent.com/1450143/66229108-62bb8f80-e6e1-11e9-8149-5742a4cf6942.JPG)

**Comment by mithro** [comment]
Do you want to add this information to either the wiki or to the docs section of this repository?

**Comment by enjoy-digital** [comment]
Yes i can do that next week.

**Comment by futaris** [comment]
https://github.com/enjoy-digital/usb3_pipe/blob/master/pocs/sniffer/sniffer.py
